<?php  
    $blockObj= $block->getLayout()->createBlock('Elsnertech\Meterial\Block\Material');
    $productId = $blockObj->getCurrentProduct()->getId();
    $getSavedMaterial = $blockObj->getSavedMaterial();
        $countvalue = 0;
    // $titles = array();
    // $color = array();
    // $per = array();

    if (count($getSavedMaterial)) {
        $titles = $getSavedMaterial['title'];
        $color = $getSavedMaterial['color'];
        $per = $getSavedMaterial['per'];
        if (count($titles) > 0) {
            $countvalue  = count($titles);
        }
    }

?>
<div style="display:none;" id="customMessage"><div class="messages"><div class="message message-success success"><div data-ui-id="messages-message-success">Save Material Successfully.</div></div></div></div>
<input type="hidden" name="productId" class="productId" value="<?= $productId; ?>">
<div style="margin-bottom: 1%;" class="row">
    <div class="save_meterial-button-container">
        <button style="float: right;" id="save_meterial_button" title="Save Material" data-role="save_meterial_button" type="button" class="action-secondary" data-ui-id="widget-button-1">
            <span>Save Material</span>
        </button>
    </div>
</div>
    <div class="admin__field">
        <input type="hidden" name="countval" class="countval" value="<?= $countvalue; ?>">
        <div class="admin__field-control">
            <div class="admin__control-table-wrapper">
                <table class="admin__dynamic-rows admin__control-table">
                <thead>
                        <tr>
                            <th>
                                <span>Title</span>
                            </th><th>
                                <span>Color</span>
                            </th><th>
                                <span>Percentage</span>
                            </th><th>
                                <span></span>
                            </th>
                        </tr>
                    </thead>

                    <tbody class="add-rows">
                        <?php $i = 0; ?>
                        <?php $j = 1; ?>
                        <?php if (isset($titles)): ?>
                            
                        <?php foreach ($titles as $title) { ?>
                            <tr class="data-row-<?= $j ?>">
                                <td>
                                    <div class="admin__field">
                                        <div class="admin__field-control">
                                            <input type="text" name="title[]" class="title" value="<?= $title; ?>">
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="admin__field">
                                        <div class="admin__field-control">  
                                            <input style="background-color: <?= $color[$i] ?>;" type="text" maxlength="6" name="colorSelector[]" class="colorSelector" size="6" id="colorSelector_<?= $j ?>" value="<?= $color[$i] ?>" readonly />
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="admin__field">
                                        <div class="admin__field-control">  
                                            <input type="number" name="per[]" class="per" max="100" min="0" value="<?= $per[$i] ?>"> %
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <button data-val="<?= $j ?>" class="action-delete">
                                        <span></span>
                                    </button>
                                </td>
                            </tr>
                            <?php $i++; ?>
                            <?php $j++; ?>
                        <?php } ?>   
                        <?php endif ?>                     
                    </tbody>

                    <tfoot>
                        <tr>
                            <td colspan="5">
                               <button class="add-one" type="button">
                                    <span>Add</span>
                                </button>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

<script type="text/x-magento-init">
    {
        "*": {
            "Elsnertech_Meterial/js/material": {
                "baseUrl": "<?= $this->getBaseUrl(); ?>"
            }
        }
    }
</script>
<?php if (isset($color)): ?>
    
<?php $k = 1; ?>
<?php foreach ($color as $c) { ?>
    <script>
        require([
            "jquery",
            "jquery/colorpicker/js/colorpicker"
            ],
            function($) {
                        $('#colorSelector_'+<?= $k; ?>).ColorPicker({
                            onChange: function (hsb, hex, rgb) {
                                $('#colorSelector_'+<?= $k; ?>).css("backgroundColor", "#" + hex).val("#" + hex);
                            }
                        });                
            })        
    </script>
<?php $k++; ?>
<?php } ?>
<?php endif ?>